### PR TITLE
Hopefully fix pshr navigation problem

### PR DESCRIPTION
**Pull request by mattdrees**
This will hopefully stop the difficult-to-reproduce problem of the user being redirected to the pshr main page, instead of the pay stubs page.
The problem does not show with a clean set of cookies. I think it shows when the user has had some kind of recent interaction with pshr.

This parameter is documented to be "used for context sensitive return to links."
Also, "NAVSTACK=Clear parameter has the undocumented feature of not updating breadcrumbs."

It's not clear to me that this will really fix the problem, but it seemed to fix it in at least one case (for Nick K).

### CODE REVIEW

**Comment by mattdrees** [comment]
@wrandall22 can you review for me? small bugfix

**Comment by wrandall22** [comment]
Looks good to me.  One thing I noticed, though, is that the base URL in staff services is `ttps://pshr.cru.org/psp/hcm92p/` and the base URL in paycheck-history is `https://pshr.cru.org/psc/hcm92p`. Are they supposed to be different?

**Comment by mattdrees** [comment]
No, they should be the same.

I goofed in the staff services `servlets.properties` that's in git. It has a trailing slash. But on the servers, `servlets.properties` has no trailing slash.

**Comment by wrandall22** [comment]
I'm talking about `psp` vs `psc` not the trailing slash.

**Comment by mattdrees** [comment]
ah, I see!

So, yes, those should be the same tool. And, on the servers, they are. The servlets.properties in git is wrong.

The link Patti originally gave me for this upgrade had 'psp'. But she was mistaken, and later told me to switch to 'psc' instead.

The differences is that 'psp' displays pshr navigation and breadcrumbs and such in addition to the component of interest, but 'psc' displays just the component.

To avoid confusion, they want to drop the navigation while in pshr. The user should close the tab when they're done, and use staff web to navigate.

**Comment by wrandall22** [comment]
Ok, so perhaps we should change the git version of servlets.properties to reflect that to avoid future confusion.

**Comment by mattdrees** [comment]
Yes, we should. I'll do that.

Thanks for the review!

**Pull request merged**
