### PR TITLE
update pshr urls for 9.2

### PR DESCRIPTION
**Pull request by mattdrees**
The 9.2 PS HCM upgrade includes a url change (both the domain and the 'sitename').

### CODE REVIEW

**Comment by mattdrees** [comment]
@wrandall22 can you review this small change?

**Comment by mattdrees** [comment]
I'll also have a ever-so-slightly longer SSW PR for you once this one gets merged.

**Comment by wrandall22** [comment]
Looks good to me

**Comment by mattdrees** [comment]
thanks!

**Pull request merged**
